### ISSUE TITLE
No support for Nodejs 4.3 ?

### ISSUE THREAD

**Issue by StefH** [Max-Kolodezniy/aws-lambda-local#1]
This tool only supports context-done, fail and succeed. There is no support for callback ?

**Comment by Max-Kolodezniy** [comment]
In development. I'll commit it tomorrow

**Comment by Max-Kolodezniy** [comment]
@StefH actually you can **npm install -g aws-lambda-local**
I've added several improvements:
1. AWS-like error output (for strings and Error object. Other objects being beautifying instead of rude "[object Object]" output)
2. Callback support including "first caller" restriction (call callback for the first time only but keep running global event.handler)
3. Exit if eventLoop is empty

```
exports.handler = function(event, context, callback) {
    callback(); // null
    console.log(1);
    callback (null); // null
    console.log(2);
    callback (null, { succ : 'ess' }); // { succ : "ess" }
    console.log(3);
    callback ('error message here'); // Error obj incl trace
    callback ({ error : 'object here' }); // Error obj incl trace
    callback (new Error('here is the message')); // Error obj incl trace
    console.log(4);
    // 1,2,3,4 output on any callback selected
};
```
